name: GitHub Actions Demo  
on: push  
jobs:  
  example-job:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Check out the repository  
        uses: actions/checkout@v3  
      - name: Run a script  
        run: echo "This job was automatically triggered!"
